[2025-01-22T11:41:52.706+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 24_runtime_environment_pools_dag.wait1 manual__2025-01-22T11:41:45.797504+00:00 [queued]>
[2025-01-22T11:41:52.817+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 24_runtime_environment_pools_dag.wait1 manual__2025-01-22T11:41:45.797504+00:00 [queued]>
[2025-01-22T11:41:52.818+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-01-22T11:41:52.901+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): wait1> on 2025-01-22 11:41:45.797504+00:00
[2025-01-22T11:41:52.934+0000] {standard_task_runner.py:60} INFO - Started process 3911 to run task
[2025-01-22T11:41:52.966+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', '24_runtime_environment_pools_dag', 'wait1', 'manual__2025-01-22T11:41:45.797504+00:00', '--job-id', '74', '--raw', '--subdir', 'DAGS_FOLDER/24_runtime_environment_pools.py', '--cfg-path', '/tmp/tmpn0ptlsbn']
[2025-01-22T11:41:52.975+0000] {standard_task_runner.py:88} INFO - Job 74: Subtask wait1
[2025-01-22T11:41:53.019+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-01-22T11:41:53.142+0000] {task_command.py:423} INFO - Running <TaskInstance: 24_runtime_environment_pools_dag.wait1 manual__2025-01-22T11:41:45.797504+00:00 [running]> on host d3a2c9f62df6
[2025-01-22T11:41:53.516+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='24_runtime_environment_pools_dag' AIRFLOW_CTX_TASK_ID='wait1' AIRFLOW_CTX_EXECUTION_DATE='2025-01-22T11:41:45.797504+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-22T11:41:45.797504+00:00'
[2025-01-22T11:42:53.578+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-01-22T11:42:53.596+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=24_runtime_environment_pools_dag, task_id=wait1, execution_date=20250122T114145, start_date=20250122T114152, end_date=20250122T114253
[2025-01-22T11:42:53.658+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-01-22T11:42:53.688+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
