[2025-01-22T10:28:26.290+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 22_sensor_dag.check_file manual__2025-01-22T10:28:19.826794+00:00 [queued]>
[2025-01-22T10:28:26.302+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 22_sensor_dag.check_file manual__2025-01-22T10:28:19.826794+00:00 [queued]>
[2025-01-22T10:28:26.303+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-01-22T10:28:26.325+0000] {taskinstance.py:2191} INFO - Executing <Task(FileSensor): check_file> on 2025-01-22 10:28:19.826794+00:00
[2025-01-22T10:28:26.333+0000] {standard_task_runner.py:60} INFO - Started process 1506 to run task
[2025-01-22T10:28:26.337+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', '22_sensor_dag', 'check_file', 'manual__2025-01-22T10:28:19.826794+00:00', '--job-id', '67', '--raw', '--subdir', 'DAGS_FOLDER/22_FileSensor.py', '--cfg-path', '/tmp/tmps7lyet2s']
[2025-01-22T10:28:26.340+0000] {standard_task_runner.py:88} INFO - Job 67: Subtask check_file
[2025-01-22T10:28:26.359+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-01-22T10:28:26.401+0000] {task_command.py:423} INFO - Running <TaskInstance: 22_sensor_dag.check_file manual__2025-01-22T10:28:19.826794+00:00 [running]> on host d3a2c9f62df6
[2025-01-22T10:28:26.496+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='22_sensor_dag' AIRFLOW_CTX_TASK_ID='check_file' AIRFLOW_CTX_EXECUTION_DATE='2025-01-22T10:28:19.826794+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-22T10:28:19.826794+00:00'
[2025-01-22T10:28:26.522+0000] {base.py:83} INFO - Using connection ID 'my_filesystem_connection' for task execution.
[2025-01-22T10:28:26.523+0000] {filesystem.py:66} INFO - Poking for file /tmp/my_file.txt
[2025-01-22T10:28:26.524+0000] {filesystem.py:71} INFO - Found File /tmp/my_file.txt last modified: 20250122102747
[2025-01-22T10:28:26.524+0000] {base.py:295} INFO - Success criteria met. Exiting.
[2025-01-22T10:28:26.535+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=22_sensor_dag, task_id=check_file, execution_date=20250122T102819, start_date=20250122T102826, end_date=20250122T102826
[2025-01-22T10:28:26.591+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-01-22T10:28:26.616+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
