[2025-01-22T11:39:20.100+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 24_runtime_environment_pools_dag.wait2 manual__2025-01-22T11:38:12.757851+00:00 [queued]>
[2025-01-22T11:39:20.115+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 24_runtime_environment_pools_dag.wait2 manual__2025-01-22T11:38:12.757851+00:00 [queued]>
[2025-01-22T11:39:20.116+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-01-22T11:39:20.146+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): wait2> on 2025-01-22 11:38:12.757851+00:00
[2025-01-22T11:39:20.155+0000] {standard_task_runner.py:60} INFO - Started process 3819 to run task
[2025-01-22T11:39:20.164+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', '24_runtime_environment_pools_dag', 'wait2', 'manual__2025-01-22T11:38:12.757851+00:00', '--job-id', '71', '--raw', '--subdir', 'DAGS_FOLDER/24_runtime_environment_pools.py', '--cfg-path', '/tmp/tmpxgs722p4']
[2025-01-22T11:39:20.168+0000] {standard_task_runner.py:88} INFO - Job 71: Subtask wait2
[2025-01-22T11:39:20.190+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-01-22T11:39:20.279+0000] {task_command.py:423} INFO - Running <TaskInstance: 24_runtime_environment_pools_dag.wait2 manual__2025-01-22T11:38:12.757851+00:00 [running]> on host d3a2c9f62df6
[2025-01-22T11:39:20.416+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='24_runtime_environment_pools_dag' AIRFLOW_CTX_TASK_ID='wait2' AIRFLOW_CTX_EXECUTION_DATE='2025-01-22T11:38:12.757851+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-22T11:38:12.757851+00:00'
[2025-01-22T11:40:20.477+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-01-22T11:40:20.493+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=24_runtime_environment_pools_dag, task_id=wait2, execution_date=20250122T113812, start_date=20250122T113920, end_date=20250122T114020
[2025-01-22T11:40:20.548+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-01-22T11:40:20.578+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
