[2025-01-21T14:50:17.871+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 04_task_sequence_morning.right_sock manual__2025-01-21T14:50:06.826875+00:00 [queued]>
[2025-01-21T14:50:17.959+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 04_task_sequence_morning.right_sock manual__2025-01-21T14:50:06.826875+00:00 [queued]>
[2025-01-21T14:50:17.960+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-01-21T14:50:18.029+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): right_sock> on 2025-01-21 14:50:06.826875+00:00
[2025-01-21T14:50:18.047+0000] {standard_task_runner.py:60} INFO - Started process 703 to run task
[2025-01-21T14:50:18.069+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', '04_task_sequence_morning', 'right_sock', 'manual__2025-01-21T14:50:06.826875+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/04_task_sequence_dag.py', '--cfg-path', '/tmp/tmp3dn39g8y']
[2025-01-21T14:50:18.073+0000] {standard_task_runner.py:88} INFO - Job 5: Subtask right_sock
[2025-01-21T14:50:18.114+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-01-21T14:50:18.206+0000] {task_command.py:423} INFO - Running <TaskInstance: 04_task_sequence_morning.right_sock manual__2025-01-21T14:50:06.826875+00:00 [running]> on host d3a2c9f62df6
[2025-01-21T14:50:18.395+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='04_task_sequence_morning' AIRFLOW_CTX_TASK_ID='right_sock' AIRFLOW_CTX_EXECUTION_DATE='2025-01-21T14:50:06.826875+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-21T14:50:06.826875+00:00'
[2025-01-21T14:50:18.398+0000] {logging_mixin.py:188} INFO - Pull on right sock
[2025-01-21T14:50:18.399+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-01-21T14:50:18.423+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=04_task_sequence_morning, task_id=right_sock, execution_date=20250121T145006, start_date=20250121T145017, end_date=20250121T145018
[2025-01-21T14:50:18.475+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-01-21T14:50:18.547+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
