[2025-01-21T21:50:22.248+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 13_parent_to_subdag.12_my_subdag manual__2025-01-21T21:50:14.768150+00:00 [queued]>
[2025-01-21T21:50:22.264+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 13_parent_to_subdag.12_my_subdag manual__2025-01-21T21:50:14.768150+00:00 [queued]>
[2025-01-21T21:50:22.265+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-01-21T21:50:22.297+0000] {taskinstance.py:2191} INFO - Executing <Task(SubDagOperator): 12_my_subdag> on 2025-01-21 21:50:14.768150+00:00
[2025-01-21T21:50:22.306+0000] {standard_task_runner.py:60} INFO - Started process 3547 to run task
[2025-01-21T21:50:22.313+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', '13_parent_to_subdag', '12_my_subdag', 'manual__2025-01-21T21:50:14.768150+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/13_parent_dag.py', '--cfg-path', '/tmp/tmpoa4015rk']
[2025-01-21T21:50:22.327+0000] {standard_task_runner.py:88} INFO - Job 47: Subtask 12_my_subdag
[2025-01-21T21:50:22.354+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-01-21T21:50:22.436+0000] {task_command.py:423} INFO - Running <TaskInstance: 13_parent_to_subdag.12_my_subdag manual__2025-01-21T21:50:14.768150+00:00 [running]> on host d3a2c9f62df6
[2025-01-21T21:50:22.602+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='13_parent_to_subdag' AIRFLOW_CTX_TASK_ID='12_my_subdag' AIRFLOW_CTX_EXECUTION_DATE='2025-01-21T21:50:14.768150+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-21T21:50:14.768150+00:00'
[2025-01-21T21:50:22.604+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2025-01-21T21:50:22.673+0000] {subdag.py:179} INFO - Created DagRun: scheduled__2025-01-21T21:50:14.768150+00:00
[2025-01-21T21:51:22.775+0000] {base.py:295} INFO - Success criteria met. Exiting.
[2025-01-21T21:51:22.797+0000] {subdag.py:194} INFO - Execution finished. State is success
[2025-01-21T21:51:22.828+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=13_parent_to_subdag, task_id=12_my_subdag, execution_date=20250121T215014, start_date=20250121T215022, end_date=20250121T215122
[2025-01-21T21:51:22.915+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-01-21T21:51:23.028+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
